uint8 TASK_TEMPORARY_PARKING = 0  # 临时停车
uint8 TASK_ADD_WAYPOINTS = 1      # 添加途经点

# 任务类型
uint8 task

# 停车周期
float32 parking_duration
# 停车点 数组长度为3时不包含经纬度信息，长度为5时，包含经纬度信息
float64[] parking_point  # utm_x, utm_y, utm_yaw, [longitude, latitude]

# 途经点
geometry_msgs/Pose2D[] way_points
float32 way_speed


---

uint8 code  # 返回码， 0: 成功 其他: 失败
string message
